name: docker-build
on:
  push:
    branches: [main]
    paths:
      - 'apps/**'
      - 'Dockerfile'
      - 'docker-compose.yml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build containers
        run: |
          docker buildx build --platform linux/amd64 -t dms-core:ci apps/dms-core
          docker buildx build --platform linux/amd64 -t chat-core:ci apps/chat-core
          docker buildx build --platform linux/amd64 -t web:ci apps/web || echo "Web build failed, continuing..."
